# Generated by Django 5.1.3 on 2024-12-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Ffood&psig=AOvVaw11HFws3BmZADUFaVy6ansj&ust=1734751345137000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCNCrzsOytYoDFQAAAAAdAAAAABAE', max_length=1000),
        ),
    ]
